### ISSUE TITLE
Buienalarm

### ISSUE THREAD

**Issue by DarkVillager** [Xorfor/Domoticz-API#11]
Sorry to do it this way @Xorfor, but your repository [buienalarm](https://github.com/Xorfor/Domoticz-Buienalarm-Plugin) has stopped working a while ago and wanted to know if you're gonna maintain it some day. Ty for reading this!

**Comment by Xorfor** [comment]
Hey @DarkVillager,

What do you mean by 'your repository buienalarm has stopped working a while ago'? The repository is still available at:

https://github.com/Xorfor/Domoticz-Buienalarm-Plugin

Or do you mean something else?

I do not really maintain the plugins anymore, because I moved to Home Assistant. But if there are any problems with one of my plugins, you can create an issue for that plugin, and I will try to fix that.

**Comment by DarkVillager** [comment]
There's an issue with the buienalarm plugin. But creating issues at that repository isn't allowed. Help?

**Comment by Xorfor** [comment]
I don't know why, but it was switched off. Now you can enter issues for the Buienradar plugin 😄.
