### ISSUE TITLE
_str2dt in server.py not working correctly

### ISSUE THREAD

**Issue by jfsant29** [Xorfor/Domoticz-API#5]
I use DomoticzAPI within a plugin.
the first pass run correctly when i desactivate-reactivate the plugin an error occurs at line 205 in module server.
solution 👍
- using import time instead of datetime
- the fonction .date() in line 205 is not necessary
- in _str2dt  replace datetime with time

**Comment by Xorfor** [comment]
I don't know what error you got. The changes you suggest are not correct, other parts of the code are invalid then. The function _str2dt  should return a datetime not a time only. The current code will pass the test.

To be honest, I paused my work on this API for a while, because of the changes in Domoticz. I wait until the Domoticz json/urls are more stable.
